OPPORTUNITY_FIELD_MAP = {
    "fid4__c": "Account Name (legacy)",
    "fid5__c": "Address",
    "fid6__c": "Primary Contact",
    "fid8__c": "Industry",
    "fid9__c": "End market reference",
    "fid10__c": "Source type",
    "fid11__c": "Armitage partner",
    "fid12__c": "Direct Source",
    "fid14__c": "Revenue estimate ($M)",
    "fid15__c": "EBITDA estimate ($M)",
    "fid16__c": "Armitage equity cheque estimate ($M)",
    "fid17__c": "EV estimate ($M)",
    "fid24__c": "Next steps and key dates",
    "fid26__c": "Date of last EOI",
    "fid27__c": "Inflection point comments",
    "fid31__c": "Status (discussions)",
    "fid38__c": "Date of Term Sheet",
    "fid40__c": "Bolt-on for",
    "fid45__c": "Reason for kill (dead deals)",
    "fid46__c": "Cold outreach",
    "fid48__c": "Status reached for dead deals",
    "fid50__c": "Employees",
    "fid51__c": "Dead deal introduced to",
    "fid53__c": "GOWT Owner",
    "fid54__c": "Debt opportunity",
    "fid55__c": "Investment date",
    "fidled__c": "Last Event Date",
    "fidprocesscreateddate__c": "Created Date (process)",
    "fidprocessclosedate__c": "Close Date (process)",
    "fidprocessowner__c": "Owner (process)",
    "fidprocessstatus__c": "Status (process)",
}

OTHER_NOTABLE_FIELDS = {
    "Company__c": "Company Overview (text description of the business)",
    "Growth_News__c": "Growth News (AI-generated news and signals)",
    "Growth_Actions__c": "Growth Actions (AI-generated action items)",
    "P__c": "Profile Activity (LinkedIn activity tracking)",
    "Business_Industry_Overview__c": "Business & Industry Overview (screener section)",
    "Financial_Overview__c": "Financial Overview (screener section)",
    "ABI__c": "ABI status (Yes/No)",
    "GOWT_Priority__c": "GOWT Priority (Low/Medium/High)",
    "Deal__c": "Deal Pipeline stage",
    "Company_Website__c": "Company Website URL",
    "Contact_LinkedIn__c": "Contact LinkedIn URL",
    "Origination_source__c": "Origination source",
    "Transaction_type__c": "Transaction type",
    "Intermediated_type__c": "Intermediated type",
    "Owner__c": "Owner",
    "Target_EOI_timing__c": "Target EOI timing",
    "Resurrection_Date__c": "Resurrection Date",
    "Re_outreach_review_date__c": "Re-outreach review date",
}
